### ISSUE TITLE
Caraya failed to register the assert event with the right unique ID

### ISSUE THREAD

**Issue by aterrazasl** [JKISoftware/Caraya#100]
Caraya Unit Test Framework version 1.0.2.115

While trying to report in the JUnit with verbose enabled, find out that the xml report doesn't include the message. Always report "test failure".

While debugging, found out that the assert register event wasn't using the right ID. After changing to Unique Assert ID (instead Test ID) the xml shows the verbose messages

![Screen Shot 2020-07-29 at 2 02 14 PM](https://user-images.githubusercontent.com/6857719/88841832-23948880-d1a4-11ea-9112-fd7896d04f79.png)

**Comment by francois-normandin** [comment]
Fixed. Will be in next release.

**Comment by francois-normandin** [comment]
Re-opening this case since a new report sheds new light on the problem in version 1.0.2.
The solution lies not in changing the "Test ID" in the test registration, but rather using the Test ID in conjunction with the Assert ID in the subsequent "update verbose explanation" method.

Adding "Unique Test ID" to the verbose cluster solves the issue but does not create a problem as reported in #110 .

![image](https://user-images.githubusercontent.com/11728548/100689825-3cc86400-3353-11eb-8657-0cce01545b4d.png)

**Comment by francois-normandin** [comment]
fixed in release 1.1.0 (build 118)
