### ISSUE TITLE
No errors when running batch test with broken VI

### ISSUE THREAD

**Issue by felipefoz** [JKISoftware/Caraya#101]
When using "Run Tests in Active Project", it doesn't throw any errors when there is a broken VI in tests.
It appears as running and then suddenly closes.
Similarly it happens with the Quick Drop Shortcut.

**Comment by francois-normandin** [comment]
Thanks @felipefoz , I had missed your report a few weeks ago...

"onTestExecution.vi" throws error 1003 if a test is broken. The error is not handled, so the Test Runner transmits an error downstream which has the effect of skipping any subsequent tests. In normal operation, this is captured as the following:

I am adding a test to specifically look for this problem. The unit test captures the failure correctly at runtime.

![image](https://user-images.githubusercontent.com/11728548/98847626-8988e100-241e-11eb-8eab-fdb193786cbc.png)

First of all, the above result is wrong because it should report the actual broken test as "Failed", not "Skipped".
Second, a unit test cannot fail, so this test will actually always produce a failure even by catching the failure... chicken and the egg problem. So the proposed solution will be to catch the broken VI error in the "Discover Tests.vi" before the Tests are actually run (with "Run.vi").

This means that the Run method does not need to execute the test to report it as failed, hence the unit test to catch this condition will pass.

![image](https://user-images.githubusercontent.com/11728548/98848136-411df300-241f-11eb-950e-3f592dcb7365.png)

Of course, the "Run Tests in Active Project" will need to watch for this specific Broken Test error code and throw a failure in the test report.

**Comment by francois-normandin** [comment]
Actually, looking in the code, I now think it is a bad idea to add this verification in the Discover Tests part as it will add a lot of overhead. Test should fail only on execution, so the Unit Test will instead need to overwrite the Runner.Folder class and handle the reporting of the failure in a way that does not Fail the unit test. Better test strategy anyway...

**Comment by francois-normandin** [comment]
Fixed for next release. The unit tests catch the broken VIs correctly.

![image](https://user-images.githubusercontent.com/11728548/98853643-7595ad00-2427-11eb-8fdc-9c50b4249b72.png)

I had to change the way errors are reported in the onTestExecution.vi of the Test Runner.
Now, Run Active Project Tests reports correctly the error.

![image](https://user-images.githubusercontent.com/11728548/98858904-5c90fa00-242f-11eb-8942-6543b9880bf9.png)

**Comment by felipefoz** [comment]
Very good to know François.
Well done.
I'll test here and let you know if I have any issues.

**Comment by felipefoz** [comment]
Hi François,

I did some testing with the new version 1.1-pre and it is working fine. As I comparison I ran the same code in the two versions.

![test not executable](https://user-images.githubusercontent.com/63814202/100383114-9e0ed100-2ffb-11eb-8d45-f23a4cc1ad89.PNG)

My other issue was related to running in CI. It was happening the same thing (tests passing) because I was using the Batch Test State Machine (the same used in Quick Drop Plugin). 

Previously, my solution was to change the test approach to the Class caller. This solution worked in 1.0.2 and in 1.1.0.

![image](https://user-images.githubusercontent.com/63814202/100385498-89353c00-3001-11eb-8bbd-9df0cc683722.png)

Thanks for always improving this tool.
