### ISSUE TITLE
Verbose info never appears in the JUnit XML or the UI display

### ISSUE THREAD

**Issue by SRM256** [JKISoftware/Caraya#110]
I cannot find any way to make the verbose information show up anywhere. I wire true to 
vi.lib\addons\_JKI Toolkits\Caraya\run-tests\Run Test (Scalar Path).vi
but I see no change in either the JUnit output or in the UI display. 

I even tried just changing the default value in the Basic Test Manager.lvclass private data to be TRUE. Still no effect. 

What does it take to make the verbose information be logged?

**Comment by francois-normandin** [comment]
@SRM256 I confirm the bug exists in version 1.0.2+.
I was able to trace the "verbose explanation" event all the way to the Test Manager's process, but the associated unique test ID is not found, so no association is performed. I'll give that a look. Thanks for the report.

**Comment by francois-normandin** [comment]
I have a fix, tested in my 2019 production machine.
I'll port the fix to the source in the coming days and this will be fixed in 1.1.x shortly.

Thanks again.

For those curious, the issue comes from the "explanation" update being keyed with the "Unique Assert ID" but the storage variant used for that is keyed with the "Unique Test ID". Since a "test" can contain multiple assertions, it didn't match.

The solution will be similar to the snapshot below (although I will look into adding the Test ID to the verbose message so that the lookup is performed faster, as a potential alternative).

![image](https://user-images.githubusercontent.com/11728548/100677286-b6068d80-3338-11eb-877f-85215b4d2fdb.png)

**Comment by francois-normandin** [comment]
Referencing #100 here, which mentions the same problem with verbose and how it is fixed by changing the Unique Test ID to Unique Assert ID.  I now think that the change in #100 is wrong, but I'll create more tests because as reported here, I believe the change needs to occur in the subsequent part (Update Test Explanation.vi)

Restoring Test ID in the registration, and updating Explanation based on Test ID & Assert ID is passing my manual testing so far, including the Caraya's own test suites: 
![image](https://user-images.githubusercontent.com/11728548/100689549-abf18880-3352-11eb-82c7-8ec0c50cf504.png)

**Comment by francois-normandin** [comment]
> 2020-11-30 21:22:45 - FAIL - Test Report Generation.vi - 
> 2020-11-30 21:22:45 - FAIL -   Verbosity - Verbosity Test.vi
> 2020-11-30 21:22:45 - FAIL -     Verbose True - {Expected: True, Asserted: False}
> 2020-11-30 21:22:45 - FAIL -     Verbose False - {Expected: False, Asserted True}
> 2020-11-30 21:22:45 - FAIL -     Verbose Not Error - {Expected: No Error, Asserted: error code = 42}
> 2020-11-30 21:22:45 - FAIL -     Verbose Greater Value - {Expected: "3"  to be greater than "4.000000", Asserted: less or equal.}
> 2020-11-30 21:22:45 - FAIL -     Verbose Equal Value - {Expected value: 3, Asserted value: 4.000000}
> 2020-11-30 21:22:45 - FAIL -     Verbose Less or Equal Value - {Expected: "5" to be smaller or equal to "4.000000", Asserted: greater}
> 2020-11-30 21:22:45 - FAIL -     Verbose Equal Cluster - {Cluster element index: 1 -- Expected value: 41, Asserted value: 42}
> 2020-11-30 21:22:45 - FAIL -     Verbose Error - {Expected: Error, Asserted: Warning 42}

**Comment by francois-normandin** [comment]
fixed in build 118 of 1.1.0
