### ISSUE TITLE
Missing VIs in Advanced VI Tree

### ISSUE THREAD

**Issue by felipefoz** [JKISoftware/Caraya#118]
Hi everyone,
Noticed that there were missing VIs in the Advanced VI Tree.

![image](https://user-images.githubusercontent.com/63814202/102495230-9bc8f100-4054-11eb-89ab-90370996ef81.png)

Anyone experienced that?
I tried in two computers, both LabVIEW 2020.
Regards,

**Comment by felipefoz** [comment]
Caraya 1.1.0

**Comment by francois-normandin** [comment]
I'm seeing the same thing @felipefoz 
_All LabVIEW Versions..._ 

I also have this dialog when I open the advanced tree, and noticed VIPM takes longer to build the package. That seems to imply that the linker is trying to find a VI that is missing, and it finally finds it in the VIPM temporary folder before it finds it in the real source folder. I've got a reproducible event, so I'll be able to sort this out.

![image](https://user-images.githubusercontent.com/11728548/109424234-dfbf6700-79b0-11eb-8073-7fc982800f7a.png)

There is also a missing class instance..
![image](https://user-images.githubusercontent.com/11728548/109424246-e9e16580-79b0-11eb-876f-2d26809c0f4e.png)

**Comment by francois-normandin** [comment]
Well... that would explain it.

![image](https://user-images.githubusercontent.com/11728548/109431548-3179e880-79d5-11eb-85fc-a02ee4f07e24.png)

I'll move those VIs to the `example` folder. The `tests` folder is excluded from the package.
Unless I include the `tests` in the package? @jimkring what is your take on this?

Advantages include being able to run Caraya tests after install. 
Disavantages include a larger package and compile time.
It seems neutral impact from the perspective of PPL build, since the tests and the Tree VIs are not part of Caraya lib.

**Comment by francois-normandin** [comment]
Included in 1.2.0 to be released soon
https://github.com/JKISoftware/Caraya/milestone/6
