### ISSUE TITLE
Assert Almost Equal should support arrays and possibly different types

### ISSUE THREAD

**Issue by bmitc** [JKISoftware/Caraya#123]
Caraya is great! It is very similar to the simple workflow of something like [FsUnit](https://fsprojects.github.io/FsUnit/) in F#, and I like the no fuss approach. I'm starting to use it in many projects now. Thanks for this package.

It would be great if Assert Almost Equal (right now it is just `Assert Almost Equal_Float.vi`) supported array types and even better if it supported other numeric types.

To implement that, malleable VIs would be the best option, but I am assuming there are strong reasons that Caraya supports LabVIEW all the way back to 2013, which makes using them not possible. (I would be hesitant to even say 2018 or 2019 are enough to properly support malleable VI usage.)

Is it possible that Caraya's base LabVIEW version will ever be bumped to at least 2018? If not, do you have some guidance for how you would like someone to implement this? For a non-malleable VI implementation, it could simply start off with the option of supporting single dimensional float arrays, which would probably be done with a straightforward polymorphic VI implementation.

**Comment by francois-normandin** [comment]
@bmitc I don't foresee yet a transition to a newer version of LabVIEW. There are still developers that back save the code to run in even earlier versions.

I think there is a solution to this though... An extension to Caraya could be created in any other version of LabVIEW and provide such functionalities. This is a project where we take great care of making changes that do not break the API, so I'm confident that any extensions built would survive changes to the base project.

If you explore that path and find you are missing something from the API, we could look at providing what's needed... At first glance, you can probably create malleable wrappers that ultimately all call the Assert True method. You might need to use the Assert Only flag within the wrapper composition.

**Comment by bmitc** [comment]
Hi @francois-normandin. Thanks for the information. That makes sense regarding the upgrade to a newer version of LabVIEW. I knew that people lagged with versions, but that's quite a dedication if people are taking libraries and resaving them in older versions than 2013. I myself am quite aggressive in upgrading systems to the latest versions.

Anyway, I see what you mean regarding simply providing an extension. That's certainly something I can do. And just to clarify, by extension, do you mean I simply provide a package of my own that requires some <x> version of LabVIEW and wraps the API, just as the top-level wrappers do?

**Comment by francois-normandin** [comment]
@bmitc Sorry I missed your follow-up question.
Yes you are correct, you can create a distributed library (package or otherwise) and extend this functionality. If your package requires a more recent version of LabVIEW, it would show up in VIPM only if your system meets the requirements.

In this particular case, it could be a single VI that uses a malleable interface instead of a variant (wrap the API as you mention). However, you might instead want to create a new copy of the method to avoid any conversions to the variant realm, for obvious speed reasons. If you do this, you might require access to some info that is protected or private to Caraya lvlib members. If this is the case, we can work to expose the functionality you need. At first glance, there might be a need to get the access to the call chain, or at least to be able to change the "level index", such as reported in #117 .
That functionality is present in the develop branch, not in the released 1.1.0 version yet.

**Comment by bmitc** [comment]
Closing this issue since it isn't an issue with Caraya, and there is a way forward with releasing a VIPM package extending the Caraya package. If/when I do so, I will provide a comment update on this issue.
