### ISSUE TITLE
Caraya Report contains duplicates of every assert regardless of hierarchy

### ISSUE THREAD

**Issue by tannerblair** [JKISoftware/Caraya#124]
When I call test VIs in a loop, Caraya seems to get confused about which parent a given assert refers to. In the image, the tree is correct. The JUnit XML contains a ton of duplicate entries

![image](https://user-images.githubusercontent.com/12645089/109082727-1ef86a00-76ca-11eb-9d80-ee35da002c2d.png)

![image](https://user-images.githubusercontent.com/12645089/109082831-4d764500-76ca-11eb-87e5-315bc7a6282c.png)

**Comment by tannerblair** [comment]
Looks like it's showing up in reports, but it's actually storing it in the results variant:

![image](https://user-images.githubusercontent.com/12645089/109083471-97abf600-76cb-11eb-89ba-42cbf5bccb9e.png)

This would go a long way toward explaining #56 since the cost would likely be on insert and this is storing exponentially more results than required.

**Comment by francois-normandin** [comment]
Can you provide a simple test code that shows this effect? I'm particularly interested in how you call the assertions in the loop and how your tests are labeled.

If there are exponentially increasing duplicates, this is a new way of working the node and naming them. It will be useful to have a solid use case in order to find a workaround at the source, like you suggest, rather than filtering them in post processing.

**Comment by tannerblair** [comment]
@francois-normandin , sorry for the complicated example. I just sanitized the code I was working on at the moment. There is actually a unit test in the PR that is the base case, but I can make a quick example in a bit and send it to you.

After debugging, the issue is how you are matching Test Events to Test Registrations. You are using the call chain, which is identical for all calls in a loop, meaning that every call matches every caller. The PR I submitted changes this to use the Test ID, which is actually unique.

**Comment by tannerblair** [comment]
Here's the base case, no loop required.
[Duplicate Reporting in Caraya.zip](https://github.com/JKISoftware/Caraya/files/6050190/Duplicate.Reporting.in.Caraya.zip)

I'll save you a click with some screenshots though:

Outer Test VI:
![image](https://user-images.githubusercontent.com/12645089/109312680-f0cf7300-780c-11eb-9ca7-ba7f990ee7b0.png)

Inner Test VI:
![image](https://user-images.githubusercontent.com/12645089/109312730-ffb62580-780c-11eb-90a7-dbe8028c1118.png)

Resulting Test Report:
![image](https://user-images.githubusercontent.com/12645089/109312790-1197c880-780d-11eb-99c9-f0ce7ee7e448.png)

**Comment by tannerblair** [comment]
Here's the same VI run in with the code in my PR:
![image](https://user-images.githubusercontent.com/12645089/109313212-94208800-780d-11eb-81dd-7371da144fbe.png)

What I changed: 

Basic Test Manager.lvclass:Generate Test Results.vi:
![image](https://user-images.githubusercontent.com/12645089/109313736-288aea80-780e-11eb-9a58-b449947fba2d.png)

New Method Basic Test Manager.lvclass:Get Test Events by Test ID.vi:
![image](https://user-images.githubusercontent.com/12645089/109313862-49ebd680-780e-11eb-89e1-021253d80ba1.png)

**Comment by francois-normandin** [comment]
@tannerblair great, thanks.
When XML was added to the project, there were only assert IDs. We later added test IDs to solve a duplicate assertions name issue across multiple tests. The XML report was not changed to match. 
I'll integrate your tests into the automated suite. Nice to know we'll have something to catch this on the future.

**Comment by francois-normandin** [comment]
@tannerblair 
confirmed, and I don't see any impacts on the rest of the framework's tests.
Funnily enough, the `Get Tests Events by Key` was already there... it turns out that the storage key is `TestID`, so no need for an extra node after all.

![image](https://user-images.githubusercontent.com/11728548/109400949-b0115000-7919-11eb-97a9-3df4f8e16a95.png)

Thanks for fishing this out. We'll have a fix for release 1.2.0.

On another note... it does not significantly change the processing time. That will be a separate issue to fix.

**Comment by tannerblair** [comment]
Great, thanks!

**Comment by francois-normandin** [comment]
Included in 1.2.0 to be released soon
https://github.com/JKISoftware/Caraya/milestone/6
