### ISSUE TITLE
Run tests in active project opens two dialogs and only displays results for the last test

### ISSUE THREAD

**Issue by LogMANOriginal** [JKISoftware/Caraya#138]
I'm using Caraya 1.2.0.129, LV2017SP1f3

When I select `Run tests in active project...`, two instances of the test runner appear. One says "No tests found" and the other runs the tests but regularly clears the screen (every 1-3 test cases). My project contains multiple libraries with individual test cases (no test suite).

![image](https://user-images.githubusercontent.com/5776685/125175011-b10c9500-e1c9-11eb-8888-6353b330021e.png)
![image](https://user-images.githubusercontent.com/5776685/125175014-b4a01c00-e1c9-11eb-9afe-e5ac5be46f6e.png)

The launcher dialog does not close and reports error 1149.

![image](https://user-images.githubusercontent.com/5776685/125175020-be298400-e1c9-11eb-97bf-938f79ff4df5.png)
![image](https://user-images.githubusercontent.com/5776685/125175074-15c7ef80-e1ca-11eb-87e2-184e424b33c4.png)

**Comment by francois-normandin** [comment]
I'd expect something like this if there is a test suite involved. It's this the case? 
Can you create a small stripped down project that reproduces this issue, and share it?

**Comment by LogMANOriginal** [comment]
In this case there is no test suite involved, only test cases in the form of single VIs.

Here is a simple project that fails for me: [Caraya#138.zip](https://github.com/JKISoftware/Caraya/files/6795897/Caraya.138.zip)

**Comment by francois-normandin** [comment]
Thanks. I'll give this a look soon.

**Comment by LogMANOriginal** [comment]
I believe error 1149 is reported because `Caraya.lvlib:Run Tests (project).vi` is never displayed. It is called by `Run Tests in Active Project.vi` from the tools menu:

![image](https://user-images.githubusercontent.com/5776685/125175591-92a89880-e1cd-11eb-8083-72caa91bf293.png)

So FP.Close fails because `This VI` returns the reference for `Caraya.lvlib:Run Tests (project).vi` and not `Run Tests in Active Project.vi`.

![image](https://user-images.githubusercontent.com/5776685/125175642-c388cd80-e1cd-11eb-9739-e1e8ffca7fa3.png)

`FP.Close` should probably be in `Run Tests in Active Project.vi`.

**Comment by LogMANOriginal** [comment]
Regarding the two dialogs, this is what happens:

My test cases call `Define Test.vi`, which spawns the test runner in the context of the project.
Because there is no test suite, the launcher calls `Define Test Suite (Default).vi`, which also spawns a test runner but in the context of the launcher.

Here is the difference between running the launcher from the project vs. the tools menu (notice the dialog at the top to display the context):

![image](https://user-images.githubusercontent.com/5776685/125176627-3fd2df00-e1d5-11eb-95c0-b36e625a69fe.png)

* Project 
![image](https://user-images.githubusercontent.com/5776685/125176526-7825ed80-e1d4-11eb-94ef-bbfe33430d39.png)
* Tools menu 
![image](https://user-images.githubusercontent.com/5776685/125176543-87a53680-e1d4-11eb-9528-9c7fa7efc756.png)

Because the context is different, variables stored in shift registers are not shared, hence the two dialogs.

**Comment by francois-normandin** [comment]
Good catch for the error 1149. Menu launcher used to close off in earlier versions but while adding a wrapper function (to solve another bug), I forgot to move the "close VI" routine in the wrapper. You're right about the context app. The wrapper threw a wrench in the initial way to handle it.

Your PR fixes the menu launcher that should be closing itself.  

It still leaves the problem of the empty test window, which is a separate issue.
I usually see the first empty window when I define a test before creating the Test Suite (here, a test suite is created by the "Run Tests in Project" tools menu. I was not expecting the second window when running straight from Tools menu.

For example, a good way to generate an empty window is to forget to enforce dataflow between a definition of a test and an assertion, such as omitting the error wire in the example below:

![image](https://user-images.githubusercontent.com/11728548/125193600-32404800-e21b-11eb-9f55-91629465190d.png)

It could also be happening if one defines a test and later uses the Run Tests method to dynamycally reference a series of tests. All tests defined before Run Test method will be in a virtual test suite and the Run Test (by Path in the example below) will run in a new test suite, which overwrites the first one. (Only a single Test Suite allowed, for now...)

![image](https://user-images.githubusercontent.com/11728548/125193738-0a9daf80-e21c-11eb-9a48-29c1a05ebc5b.png)


But in this case, this is not the cause. The empty Test Manager UI is not supposed to show up at all. It looks as if it opens a Test Manager in both the NI.LV.Dialog context and the project's context. The NI.LV.Dialog does not contain any tests, so it reports empty. It should not try to search and run in this context at all. I'm dumbfounded that I didn't catch this in the testing for 1.2 release. A patch needs to be done because it looks like it defaults to interactive, which would surely not play nice with CI deployments.

**Comment by francois-normandin** [comment]
Hmmm, disconnecting the "AppReference" in the TestRunner's "onTestExecution" method seems to solve the issue, but in a way that is not the intended context. 
It confirms that the empty Test Manager UI you reported is in the LV.Dialog context. Disconnecting the reference means that the tests are all run in the NI.LV.Dialog context instead of the project's context.

The intent was to run them in the project's context to avoid locking classes and recompiling any VIs that are using separate cache files in the IDE. 

I found the issue: The Assert Factory Manager is a singleton and does not have app reference support yet. What happens is that a Test Manager is created in the NI.LV.Dialog context and should be created instead in the project's context. Once the first test is created, the singleton is still uninitialized in the project's context, so it is created there as well. Two instances are run. The only solutions are:
1. Run everything in the NI.LV.Dialog context
2. Feed the app reference to the Assert Factory Manager

Solution 1 is a quick fix to anyone that cannot wait for the Solution 2 to be implemented, but it comes at the penalty of recompiling in a different context, and locking classes until the context reference is terminated.

For those that would want to enact this temporary fix on their local disk, simply delete this wire: 
![image](https://user-images.githubusercontent.com/11728548/125195140-5f442900-e222-11eb-9c82-231665661512.png)

But if you can wait a couple days, solution 2 should be coming soon.

**Comment by francois-normandin** [comment]
OK, initialize proof of concept to implement the context-safe singleton Assert Factory yielded a crash of LabVIEW... (just to keep all in the loop) ;-)
Can't fix this today, but it's on the top of the pile.
Thanks @LogMANOriginal ... I'll be able to merge your PR as part of this investigation.

**Comment by LogMANOriginal** [comment]
Here is a solution that works for me. It calls the test runner by reference in the context of the project. Not sure if there are any gotchas.

![image](https://user-images.githubusercontent.com/5776685/125198941-52482980-e264-11eb-9664-6add552f5d9f.png)

The other tools menu items could work similarly.

**Comment by francois-normandin** [comment]
That might very well be the simplest fix. 👍 
I'll cross-verify, but I'm confident it shouls. Would you care to amend your PR and resubmit with this fix included?

**Comment by LogMANOriginal** [comment]
Done.

**Comment by francois-normandin** [comment]
FYI: @LogMANOriginal I sent you a PM in LAVAG.org.

**Comment by francois-normandin** [comment]
The proposed solution works in IDE, compiled as a PPL and built into an EXE. No breakage or undesired effects.
I don't currently have a mean to test on an RT target, but since there is no interactive UI supported on RT (and no Tools menu either), I will skip this and proceed with a release 1.2.1 patch.
