### ISSUE TITLE
Force Verbose

### ISSUE THREAD

**Issue by SebMichaud** [JKISoftware/Caraya#158]
Verbose is available only for failed tests.
It could be cool to have an option to force verbose on all tests even the passed ones.
That leads to a complete report which can be required in some industries.

**Comment by francois-normandin** [comment]
@SebMichaud , 
The current implementation for verbose reporting is to state the expected and asserted values. It does seem redundant do state the obvious when a test passes, such as` Expected: True, Asserted: True`. Granted, the "Assert True" is the most basic and surely you are referring to less trivial use cases such as "Assert Greater or Equal than". The verbose failure would report something alongside this: `Expected: "%s" to be greater or equal to "%s", Asserted: less` 

I'm wondering if it might be possible to explore a way to implement #151. As it is, issue 151 cannot be added because it means an extra terminal on the connector pane (which is impossible for some nodes already), but also because it would need to be wired explicitly. I think the use case I'm reading here is that there is a need for generating richer reports verbiage with actual values asserted, as well as potentially overwriting this auto-generated verbose log with a user-defined content.

Does this capture the intent of your request?

**Comment by SebMichaud** [comment]
Yes that's it.
I could summarize it like that : output a report just like TestStand do.
For each result : one name, one measurement, one or more limits, and one status.
For the True/False assessment : TestStand always expect True, there is no False assessment.

**Comment by francois-normandin** [comment]
This is featured in in [1.4.0 RC1](https://github.com/JKISoftware/Caraya/releases/tag/1.4.0_RC1)
https://github.com/JKISoftware/Caraya/discussions/172

(Not yet released on VIPM Community.)
