### ISSUE TITLE
A space character in test-label moves the result row to inappropiate location in result tree

### ISSUE THREAD

**Issue by digiajay** [JKISoftware/Caraya#160]
As screenshoted in the below caraya test, a space character before test-label moves the caraya result tree
![image](https://user-images.githubusercontent.com/6551395/229292918-e3cd1780-cd52-4582-bc54-c8445de3a7d6.png)

The expectation would be a proper result tree.
![image](https://user-images.githubusercontent.com/6551395/229292984-7ce16bc6-6f58-43e7-8496-ea8a9f398c5d.png)

**Comment by francois-normandin** [comment]
Thanks @digiajay , 

I found the location where this bug is introduced. In the "Register Test", Caraya calls the Assert Factory and looks into the call chain to associate itself to a parent test (Caller UID). There is a Match Pattern node that uses ".vi " (with an extra space char at the end).
I am unsure if this was done on purpose to support VI reentrancy, or it is a typo. Pretty sure this is why the caller skips a level in your example. A fix will be available in the next release.

**Comment by francois-normandin** [comment]
This is fixed in [1.4.0 RC1](https://github.com/JKISoftware/Caraya/releases/tag/1.4.0_RC1)
https://github.com/JKISoftware/Caraya/discussions/172

(Not yet released on VIPM Community.)
