### ISSUE TITLE
Comparison of numbers of different types (representation)

### ISSUE THREAD

**Issue by kosist** [JKISoftware/Caraya#21]
While comparing equal numbers which have different representation (like, I32 and U32), assert "is equal" fails. Although, normal LabVIEW comparison passes.
![assert equal numbers](https://user-images.githubusercontent.com/1911151/39705700-75307f76-520f-11e8-951a-e8a3413b0d03.png)
Such behaviour is not documented (it is not stated, that representation is taken into account), and as for me could be confused...
I understand the issue with floating point numbers, but in case of integers maybe it's possible to solve somehow?
What could help - is when assert fails because of representation, then write it in report string (error message); or to have "is equal" assert as polymorphic, with inputs of same particular numeric types.
Or, maybe there are some other solutions...

Thanks a lot,

Sincerely, kosist90

**Comment by francois-normandin** [comment]
There seems to be two school of thought here. 

[NUnit](http://nunit.org/docs/2.2.5/equalityAsserts.html) considers that equal values of different types should assert to TRUE.
In C#, a Equals assertion is considered the same as a [ReferenceEquals](https://docs.microsoft.com/en-us/dotnet/api/system.object.referenceequals?redirectedfrom=MSDN&view=netframework-4.7.2#System_Object_ReferenceEquals_System_Object_System_Object_) assertion, which would assert FALSE  to a comparison between U8 and a U16 because they are not equal in the memory space.

Since LabVIEW is fundamentally a byValue language, I would prefer that the AssetEqual would return TRUE in this case. This would further be inline with comparing floating-point representation numbers with a certain degree of precision ( issue #11 ).

**Comment by francois-normandin** [comment]
NodeJS adds [AssertDeepEqual](https://nodejs.org/api/assert.html) to force type to be the same.

**Comment by francois-normandin** [comment]
Here's what the Assert Equal primitive does:
![image](https://user-images.githubusercontent.com/11728548/46892251-cbf42400-ce3a-11e8-8cbb-6be2ebbed2fb.png)
If the variant-casted inputs are not strictly equal, it will assert False.

I just had a live chat with @jimkring about this. We asked ourselves what the average developer would expect from the "Assert Equal" method, and we feel it matches more closely the NUnit definition. However, the granularity that is given with asserting the type seems important.

### The proposed solution:
We are going to deprecate the "Assert Equal" primitive and hide it from the palette. By doing so, no changes will occur for any deployed test code out there.
We're going to propose two new methods to replace it: "**Assert ValueEqual**" and "**Assert Value&Type Equal**" (exact names to be determined). This will give more granularity to developers in asserting precisely what they intend to assert.

This feature will be included in the next release.
Thanks to @kosist for reporting this.

_Community's comments are welcome. Tell us what you think!_

**Comment by jimkring** [comment]
@francois-normandin @kosist I've created a Change Specification document to outline the problem, assumptions, considerations, and solution. Please review: https://github.com/JKISoftware/Caraya/wiki/Change-Spec:-Add-Support-for-Assert-Equal-Value-in-Addition-to-Assert-Equal-Value-and-Type-(Issue-%2321)

**Comment by francois-normandin** [comment]
I will close this topic as it is now being tracked in issue #25 .
Please leave comments there for further discussion.
