### ISSUE TITLE
Disable Error generation when assert fails

### ISSUE THREAD

**Issue by OlivierLabo** [JKISoftware/Caraya#22]
It should be an option to disable error generation on assertion failure.
If we assume that only Assertion on GUI, or in Test suite report file is enough.

Moreover, when we want to sequence several assertions in the same test case, creating dataflow with error cluster, the error generation creates error tests.

There is a unused boolean input "Assert Only" on assertion VIs. What is the desired future purpose of this input? Could this be a way of inhibit error generation?

Finally, is there a reason for test results not to be sorted in executed order in final result GUI ? when executing several assertions in sequence, we expect results to be sorted in the same way.

Caraya 0.5.1.31

**Comment by kosist** [comment]
I guess that error generation on assertion failure - is key point of assertion; but maybe I'm wrong. This is also how it is done in other languages, so it should be general approach.

**Comment by francois-normandin** [comment]
I second that. 

The goal of a unit test framework is to prevent a build being done when at least one test fails, and to inform the developers early. 
Propagating the error to prevent future tests from running is also meant to ensure that your future tests are not failing because of the previous failures in your sequence. Especially in the context of build automation where compilation is resource-intensive, you want to stop a build process early and make those resources (aka CPU time) available for the next commit. 

This default behavior of the test framework allows a developer to build tests that completely rely on the result of previous tests to build a stronger case that the code is working according to specs.

**Comment by Gabnaim** [comment]
Since Caraya is just LabView code, you can build your tests either to pass errors through, or to ignore them, depending on your needs.

I turn off automatic error handling and use a sequence diagram to run my tests, without passing errors between them. This ensures that tests run independently, and if one fails, the rest still runs. It also looks cleaner.

To check if the entire run has failed, I pop a sequence diagram with three frames on the top level. Open a test suite in the first. Put the top level test runner in the second. Put destroys suite in the last. Wire from first to last the error and the test suite wires. When you destroy the test suite, it will have no error if it was successful, and an error if it failed. This can be used for automatic test execution.
