### ISSUE TITLE
"time" in JUnit report always "0.000" (version 0.6.1.51)

### ISSUE THREAD

**Issue by drjdpowell** [JKISoftware/Caraya#34]
There doesn't seem to be anywhere where "time" is set, and thus it is always zero.  I assume this meant to be the test execution time?

**Comment by francois-normandin** [comment]
Indeed it is.

Since Caraya's assertions are run without a SetUp or TearDown, and they do not "launch" a unit of test but rather only execute when the result of the assertion is known... there is no concept of "execution time" in Caraya. 

Caraya's JUnit report should be thought more as a JUnit-compatible report meant to satisfy the requirements of JUnit report plugins on automated build servers or visualization tools.

**Comment by drjdpowell** [comment]
Q: can you just leave the "time" out?  

Alternately, use the timestamp from the "Define Test" call of the containing VI as a start time.

**Comment by omarmussa** [comment]
Actually if the Polymorphic Assert had an optional "Execution Time" input then test developers could use whatever execution performance benchmark they wanted to track into the results/JUnit report and that could be really useful.  I agree that if the time = 0.000 then it should be stripped from the report (or the default should be NaN and NaN values should be stripped from the report -> that would be even better in my opinion).

**Comment by jimkring** [comment]
I have some thoughts/questions about this. It seems there are some possibilities for adding an "Execution Time" input, which I've tried to capture below. I welcome other thoughts on this.

Note: **My preference** would be to have an "**Execution Time (s)**" input of a **Double Floating Point** type and a **Default Value of -1.0** (instead of NaN, since NaN can sometimes be an output of calculations and helpful to see when things go wrong). 

Various Possibilities I can think of.

Type: Double
Default value: 0.0
Behavior: Do not show in JUnit report if isZero?(Execution Time) == TRUE (using LabVIEW Equals Zero comparison)
Cons: Sometimes execution times are very small (too small to measure) and it's helpful to see when that's the case.

**Jim's Preference**
Type: Double
Default value: -1.0
Behavior: Do not show in JUnit report if isLessThanZero?(Execution Time) == TRUE (using LabVIEW Less Than Zero? comparison)
Cons: can't think of any

Type: Double
Default value: NaN
Behavior: Do not show in JUnit report if isNaN?(Execution Time) == TRUE (using LabVIEW Less Than Zero? comparison)
Cons: Nan is sometimes returned in calculations and can be helpful for debugging.

Type: Variant
Default Value: Null Variant
Do not show in JUnit report if isNullVariant(Execution Time) == TRUE
Show in JUnit report if any numeric value (e.g. 0.000, NaN, -1.0 etc)
Cons: It's not obvious to users that this input expects a numeric in units of seconds -- can't right-click on it and create constant of numeric type.

**Comment by omarmussa** [comment]
I’m liking the -1 as the default and not showing in report if -1 for the reasons you stated.

Thanks,
Omar

Written on my mobile phone, please excuse any typos.

**Comment by francois-normandin** [comment]
Implemented in 1.0 branch with Jim's suggestion of default execution time to "-1".
- Added to all assertions
- Modified the JUnit report to filter time when < 0.

![image](https://user-images.githubusercontent.com/11728548/70145388-f07a1380-166d-11ea-9f4e-589f7ed121e4.png)
