### ISSUE TITLE
Sequential tests show error for upstream failures, by default

### ISSUE THREAD

**Issue by jimkring** [JKISoftware/Caraya#36]
A user communicated that the default behavior of showing an error if a test has an upstream failure is not really the desired behavior.  If you want to suppress this, you have to set the error code to 0. I'm not sure of the best solution, since changing the behavior might cause problems for users who might rely on it.

![image](https://user-images.githubusercontent.com/381432/51642748-1a778b00-1f1f-11e9-9987-a983d6592500.png)

FYI @francois-normandin

**Comment by francois-normandin** [comment]
I would refer to this discussion #22. 

My personal point of view has not changed since. (Happy to hear what other people think about it)
If one wants to run all tests, they should be run in parallel. If one wants to ensure that a test suite fails quickly and not waste CPU time testing code that fails at least one part of it, then it should skip downstream assertions.

The fundamental reason is that one should build on previous assertions to make a stronger case that their VI/Node/Subsystem/Application works the way it should. If you have an upstream assertion that fails, then you cannot infer that the downstream ones will work correctly unless they are completely independent from previous inputs.

Ex: Take the following test where the two assertions are not independent:
![image](https://user-images.githubusercontent.com/11728548/51647059-490a5b80-1f49-11e9-97d5-8daf9c584aaa.png)

This test gives the correct result:
![image](https://user-images.githubusercontent.com/11728548/51647103-72c38280-1f49-11e9-959e-b750b7201521.png)

This one does not:
![image](https://user-images.githubusercontent.com/11728548/51647126-8a027000-1f49-11e9-880d-088159621ceb.png)
(0/0 is not greater than 1... it can be, but it is impossible to know without further algebraic investigation)

In the example above, the first assertion makes a determination on the validity of the operation that follows. They are not independent assertions. Having a default value of "0" for error code would force the developer to add an extra input to this terminal every time.

To develop a bit on this, there are many use cases for using assertions. Let look a few of them:

**Assertion is part of a TestSuite that is run by a build server.**
If a single test fails, then the build should not proceed. The build server should abort the build and return an error for developers to take action. If assertions are used in a large and extensive application with many subsystems under test, it should not waste CPU time running tests on a revision of the code that will not be deployed.

In the case that developers still want to test each subsystems (to tell them which subsystems fail and which pass), then they should be run in parallel to each other.

**Assertion is part of an application**
If the assertions are inserted in code that executes (either in IDE or at RunTime), then they are nodes just like any others. An error at the input bypasses the code in the node and thralls the error to the output. Unless a method's function is to act on an error or modify it, then it should leave it alone.

**Assertions are independent of the following assertions**
They should be run in parallel with a merge error function.
The best example is the one that tests Caraya... We want to know which one of many independent assertions fail or not. When we come up with a new test, we add it to the list of parallel tests to run.

![image](https://user-images.githubusercontent.com/11728548/51647394-9affb100-1f4a-11e9-9be9-66a10d0ce466.png)

**Assertions are part of a large application with many subsystems**
Run each Subsystem Test in parallel.
![image](https://user-images.githubusercontent.com/11728548/51647431-c97d8c00-1f4a-11e9-8c4d-1afc972c417f.png)

**Comment by jimkring** [comment]
Great points. Thanks for the depths and clarity of the explanation.

**Comment by neilpate** [comment]
I also encounted this issue when first starting to create tests, and was surprised the error propogated. However after thinking about it a bit I just did everything in parallel and merged the errors together.

I actually only use the error cluster to sequence higher levels of VIs containing tests, and generally just wire it straight through a test VI and turn off automatic error handling.

**Comment by jimkring** [comment]
Thanks, @francois-normandin and @neilpate.  I agree with all this. I guess my next wish is that LabVIEW (and the auto-wire quick-drop Ctrl+Space >> Ctrl+W) could be improved to make all the parallel error wiring a bit easier.

**Comment by francois-normandin** [comment]
Closing this discussion.
