### ISSUE TITLE
Destroy Test Suite throws error 1 intermittently

### ISSUE THREAD

**Issue by omarmussa** [JKISoftware/Caraya#4]
Destroy Test Suite throws error 1 intermittently.

For some reason, the following code:
<img width="570" alt="caraya bug" src="https://cloud.githubusercontent.com/assets/7425007/16711697/ddccb342-461d-11e6-8826-8b76f52fbccf.png">

Throws Error 1 on occasion with the following description: "Generate User Event in Caraya.lvlib:Basic Test Manager.lvclass:Close Test.vi->Caraya.lvlib:Test Suite.lvclass:Destroy Test Suite.vi->Untitled 1"

Expected behavior is that it throws Error 42 with the following description: "Caraya.lvlib:Test Suite.lvclass:Destroy Test Suite.vi<ERR>
Test Suite Failed".

The Error 1 is generated randomly/intermittently.  Tested running on LabVIEW 2015 SP1f3.

**Comment by jimkring** [comment]
I just did a test and if I run this bit of code continuously, the Destroy Test Suite will hang (at some point) waiting on the notifier. I suspect that there is a race condition somewhere in synchronizing the startup and shutdown of some asynchronously run VIs, with respect to managing references. Will need to look into this some more. FYI @francois-normandin

**Comment by francois-normandin** [comment]
The issue turned out to be that the "Test Event" factory needed to be cleared during destruction of the test suite. 
The bug was not happening if sufficient time was left between each run, probably due to the time taken by the IDE to handle (and discard) stale references. The Test Events are stored in a variant attribute FGV, which might be a factor. Resetting the factory was enough to solve the issue.
