### ISSUE TITLE
Main UI : Test cases are not sorted according to when they occur

### ISSUE THREAD

**Issue by CygaLV** [JKISoftware/Caraya#40]
Hi!
It seems that the tests results are not listed in the order the test occured.
It looks like it is sorted ny name instead. Which is confusing when there is a specific test sequence coded in the test VI.
![carayatestsequence](https://user-images.githubusercontent.com/20690677/52906250-f2293680-3215-11e9-8193-b6280b88dcaa.png)

**Comment by jimkring** [comment]
@CygaLV I can see what you're saying, here.  Yes, it would certainly be helpful to see the results organized in a more chronological fashion.  Since Caraya is really designed to test in parallel, I think that this was a design choice to help people find the tests easily by name.  I can see how it would be nice to see them sorted chronologically, and also it would help if there were a search box to allow tests to be easily found by name.

Let me ask: Is this lack of chronological sorting actually causing you challenges in your development? Can you walk me through your development/testing use case, where you need to find these tests in the tree view and having them in chronological order is helpful?

Thanks for answering that question. It helps us make sure that Caraya is helping you get your work done faster :-)

CC: @francois-normandin @JKISoftware/jki-staff

**Comment by francois-normandin** [comment]
To my knowledge, it was not a design choice but rather simply the result of using a Variant Attribute as the storage mechanism for Node results. The node name being the key identifier, the resulting list for each level of the hierarchy is sorted.

If it were changed to be represented by the execution order, it would change the order of results when the assertions are run concurrently within the same test VI. In Cyril's (@CygaLV) example, "ping alone" and "create db" might not always appear in the same order. Can we live with that? Personally, I don't think it would a problem to change to time-based ordering. I also feel it is more natural. After all, we are not diff'ing our results with the previous one to infer whether a suite of tests has passed...

**Comment by jimkring** [comment]
Thanks for chiming in on this @francois-normandin. I, too, think that time-based ordering feels more natural to me, too.

Side note: I could see some use cases for wanting to view results in alphabetical order, too, however, I try hard to avoid too many bells and whistles on the UI (I'm preemptively trying to avoid adding a "sort by" option to the UI) since, IMO, the primary goals of software unit testing is (1) know if the code passes all tests (Yay!) or not and (2) to know which specific code (if any) has failed. The UI should make knowing these two things as easy as possible, and any other features should not come at the expense of these two primary goals.  There, I said it :-)

**Comment by CygaLV** [comment]
Hi !
I understand the parallel nature of Caraya, but as stated in aprevious post (on Twitter, sorry for the cross communications) testing sometimes require a context and all tests in the world cannot be made in parallel.

I've been testing more my library lately and my previous assumption was wrong : it is not sorted alphabetically (see image).
So, according to what I see, it is not sorted alphabetically nor chronologically.

Sorting tests chronologically, IMO, is very important. When you have a huge test tree with tests running in parallel and intermittent fail cases, it might come from actions running in a specific order (which might not be controllable if your code is really fully parallel). With the timestamp it can help finding a timig pattern to failure situations.
When you test tree is sequential, it also helps a lot reading the tests results in the order of result generation.

I understand that the purpose of Caraya is to give a OK/NOK status and you do not want to add too many features in the GUI itself. Maybe having a second column in the tree view with the timestamp of **result generation** would be a first step ?
![2019-02-19 09_35_51-window](https://user-images.githubusercontent.com/20690677/53024572-4823f700-342d-11e9-935e-ef8a05be1bc0.png)

**Comment by francois-normandin** [comment]
This is implemented in the 1.0 branch. It will be fixed for that release.
