### ISSUE TITLE
Caraya report overwrites previous report if the Test Manager UI is open prior to test execution

### ISSUE THREAD

**Issue by jcopetre** [JKISoftware/Caraya#46]
The attached demonstrates this quite well. For my purposes, this is a minor issue as I can simply close the UI in between each execution of my test set though this isn't the expected behavior.
[Caraya Report Write Failure.zip](https://github.com/JKISoftware/Caraya/files/3623666/Caraya.Report.Write.Failure.zip)

**Comment by francois-normandin** [comment]
@jcopetre 
I know this is an old thread. This is mainly for documentation reasons.

This is expected behavior.

The use case is for a developer that makes a tiny change and tries to see the impact of that change on a series of conditions. This developer wants to be immediately seeing the results with a minimal number of clicks. By writing over the previous results without closing the window, you can stay focus on modification of your VI under test, and simply hit the run arrow to see the result. No clicks needed anywhere.

To produce multiple windows, you'd need multiple Test Suites.
To append the results to the same UI, cumulatively, you'd be duplicating the test IDs, so you would need to run your tests with re-entrancy enabled to produce different test IDs on each run.

**Comment by jcopetre** [comment]
Thanks for the feedback.  As you've described, the "feature" is undocumented behavior which is counterintuitive from the core object interface. Instantiation of the Test Suite is conducted via the _Defined Test Suite_ constructor which exposes a _Report Path_ input and, as well, destructor in _Destroy Test Suite_; all of this implies that changing the file name (such as, in my case, appending a timestamp to it at instantiation) and subsequently destroying the object on test completion should result in a new test report file on the next run.
