### ISSUE TITLE
Add Button to Rerun All Tests from Results Window

### ISSUE THREAD

**Issue by jacobson3** [JKISoftware/Caraya#48]
I think it would be a nice feature to be able to rerun all tests from the results window without having to  find and run the specific test VI. I was able to hack together a quick proof of concept which shows the idea. In the Basic Test Manager: Process.vi I first duplicated the Test; Open case to create a new Test: Rerun case. It's basically the same code that calls the run method instead of the open method (also includes changes from #47).

![RerunTests](https://user-images.githubusercontent.com/25009788/67884216-75c05480-fb13-11e9-9e2c-2c38444f9888.png)

This case is called from the event structure which passes the first element of the TestTree.AllTags property as an argument. This should have the effect of passing the tag of the root tree item.

![RerunTestsEvent](https://user-images.githubusercontent.com/25009788/67884228-78bb4500-fb13-11e9-878c-04d8249ad681.png)

**Comment by francois-normandin** [comment]
This will be added to the branch 1.0.
Since the addition of a Verbose flag in the Test Suite, the UI cannot export a verbose report unless the developer had specified it up front.
Doing a rerun of the tests should include the possibility to change the verbose flag and export results to file with detailed explanations as shown in #43 .

**Comment by francois-normandin** [comment]
I implemented your solution @jacobson3.

![image](https://user-images.githubusercontent.com/11728548/71209733-49ef5e80-227a-11ea-8961-487b0847ece5.png)

However I haven't found a simple and easy way to rerun the test _with verbose mode._
It requires wrapping the current test in a Test Suite (to set the verbose flag) after verifying that it was not already a test suite (because recursive test suites are not supported). However, the way that the Basic Test Manager currently works, doing so requires a new notifier reference to be registered by the UI. Implementing this sort of change with the current architecture would require a hack that I am unwilling to make (breaks encapsulation). I think this "subfeature" (change verbose flag from the UI and rerunning the tests) requires first a complete decoupling of the UI from the Test Manager core. My suggestion is to leave that for future development.
The only other clean way to do it is to always compute the "verbose" description, by default, but doing so increases the computation time and diminishes the value of the assertion framework when used in production code with the "Assert Only" flag set to True.
