### ISSUE TITLE
No more compatibility with real-time targets

### ISSUE THREAD

**Issue by OlivierLabo** [JKISoftware/Caraya#65]
I was used to run some unitary tests on real-time targets (PXI & cRIO)
Since I upgraded to 1.0.63, Vis are broken.

Lot of things about menu selection are not compatible with real-time targets in JKI Toolkits\Caraya\classes\Basic Test Manager\Process.vi

**Comment by francois-normandin** [comment]
@OlivierLabo , thanks for the feedback!

I think those menu-supporting cases were added to handle verbosity and restore the last choice from a config file (developers preferences).
This feature cannot be implemented because the verbosity needs to be set before running the tests, not only as a flag prior to producing the test report. 
These cases should have been deleted completely from the process VI. 
I'll make sure the process is compatible with RT again.

**Comment by francois-normandin** [comment]
Compatibility restored in pre-release build 72
https://github.com/JKISoftware/Caraya/releases/tag/1.0.0.72

![image](https://user-images.githubusercontent.com/11728548/72807725-05aeff80-3c26-11ea-8041-e45c076b1533.png)
