### ISSUE TITLE
Could Verbose Result be displayed in Caraya GUI

### ISSUE THREAD

**Issue by OlivierLabo** [JKISoftware/Caraya#73]
When using Verbose option, verbose details are only available in Report files.
It could be useful to have them displayed directly in the Caraya GUI.

**Comment by pollockm** [comment]
+1.  Yes please.

**Comment by pollockm** [comment]
My use case would be satisfied if the details are available as tooltip for the individual test case

**Comment by francois-normandin** [comment]
I was thinking about this for the next release down the line when I was proposing #72.
I'll explore Matt's suggestion since it does not change the UI presentation. I'd very much like to avoid more UI work until the Test Manager's core and the UI layer are decoupled. After that separation of concerns, it would be possible for the community to propose different skins and representations for the results. I'm hoping I find time soon to start this. I'm pacing myself because it will require a whole bunch of different testing to ensure we don't break anything doing so.

**Comment by francois-normandin** [comment]
I'll keep this one on the backburner for now. The Test Manager's process is the tricky VI to manage when it comes to supporting RT targets. Definitely, decoupling the manager and UI will open up a lot of opportunities for improvements of the sort.

**Comment by tannerblair** [comment]
Also very interested in this. Currently having to create my own "verbose" reporting using the label, but it makes for ugly test code and more room for human error.

**Comment by francois-normandin** [comment]
I'm going to close this request as there is now a Report tab in the main UI (Caraya 1.4.0) which displays the verbose explanations and other Assert Properties.
![image](https://github.com/JKISoftware/Caraya/assets/11728548/838a16ac-442e-4c38-a895-4626406a360b)
![image](https://github.com/JKISoftware/Caraya/assets/11728548/06162899-41cd-4264-91cc-93028525c441)

Check out the Advanced Properties palette and the examples.
![image](https://github.com/JKISoftware/Caraya/assets/11728548/471b0f55-2be9-4947-8262-dcd7738f0363)

**Comment by jimkring** [comment]
Very nice! 👍🏻 --
Jim Sent from my mobile.
