### ISSUE TITLE
Test Suite hang if skipped tests

### ISSUE THREAD

**Issue by pollockm** [JKISoftware/Caraya#74]
If there is a skipped test (for example, in a case structure), the Destroy Test Suite function hangs on Wait on Notification, which has an infinite timeout.

Example:
![image](https://user-images.githubusercontent.com/5288961/73202233-38626780-4100-11ea-88b7-ba06a933cc86.png)
(where the case structure runs tests in the no error case)

This currently hangs my CI system, so a timeout with an error would be better.

**Comment by francois-normandin** [comment]
I'll add error "7003" : "Test Manager shutdown timed out".

I don't want to add a timeout terminal to the "Destroy Test Suite" method because it is dynamic dispatch, so I'll make it default to 1000ms. I doubt very much that anyone has overwritten this node, but for the sake of backward compatibility, I'll add a public accessor to change the timeout if the developer needs a longer or shorter one.

**Comment by francois-normandin** [comment]
done
