### ISSUE TITLE
Escape testcase label or throw error

### ISSUE THREAD

**Issue by pollockm** [JKISoftware/Caraya#79]
If using a testcase label that contains quotes ("example"), the output JUnit XML will be invalid and fail XML parsing.  

The XML output generator should either escape the string or throw an error saying that quotes are not allowed.

**Comment by pollockm** [comment]
So instead of "example" it would output \"example\"

**Comment by francois-normandin** [comment]
According to Stack Overflow, there are only five escaped characters in XML: 
```
"   &quot;
'   &apos;
<   &lt;
>   &gt;
&   &amp;
```

**Comment by francois-normandin** [comment]
Will be fixed in next release.
Before:
![image](https://user-images.githubusercontent.com/11728548/75209856-66fa4f00-574d-11ea-843c-c9ce0606a46c.png)
After:
![image](https://user-images.githubusercontent.com/11728548/75209863-6c579980-574d-11ea-9347-9e3442598ab8.png)

I've added escaping verification for verbose explanations, descriptions, class names and text labels.

**Comment by francois-normandin** [comment]
Done and tested in Caraya 1.0 build 105.
