### ISSUE TITLE
When executing a test suite, get results of single tests as they finish

### ISSUE THREAD

**Issue by joerghampel** [JKISoftware/Caraya#95]
I'm working on integrating Caraya into our CI toolchain (our [Release Automation Tools](https://rat.hampel-soft.com)). Each of the CI tools is basically a wrapper VI for a single stage (test, analyze, build...). Those VIs are executed from GitLab's runner via G-CLI, and will write any output back to G-CLI and to a string indicator on the VI's front panel. 

We've been using Caraya Test Suites so far, so each project has a UT_Main.vi that contains a test suite and the tests to be run. The CI tool now calls this UT_Main.vi by reference (with interactive set to false). At the moment, I can evaluate the error cluster after the test suite has finished, and/or look at the report that's created.

I'm missing a way to get to the results of the various test steps as and when they are executed. I'd be happy with a straight-forward public event, as I want to consume this information directly in the VI that's calling/executing the tests.

**Comment by francois-normandin** [comment]
@joerghampel Thanks for the suggestion.
I think it is a great idea and I look forward to exploring it. 

There are already a few hooks under the hood that we could leverage for this with a little refactoring. Test Manager (core test engine) uses events to register and update test results as they are pouring in. Finding a solution that publishes the test results as they come in is inline with the direction Caraya's core engine is going to take in the near future. Your request is completely in the same workflow as suggested by #72 which essentially assumes that there is a way for views to feed on the core test engine's results in real time.

**Comment by francois-normandin** [comment]
Next release will include two ways to grab a Test Suite's test results: 

1- Directly from the destroy suite method
2- From a Suite's test result event. (The event cluster will have "Suite destroyed" and "Test Result" events for now)

![image](https://user-images.githubusercontent.com/11728548/98876352-18f8b900-244c-11eb-8274-4ea8c21d807d.png)

I did not dwell on modifying the result's cluster (nodes and assertions) because the Test Manager refactor is still pending, so I didn't want to coerce the future design unduly, as we'll need to preserve backward compatibility.
I'll explore the potential to inject a Test Result type at the Suite's creator so that the Test Result class itself could be overloaded (allowing the process of results in a more user-friendly manner by creating user-defined overloads). Currently, it resolves through a variant datastore, and the result array is not wrapped into a neat class... (to be continued)

The Advanced VI Tree shows the Test Result as an output of Suite Destruction.
![image](https://user-images.githubusercontent.com/11728548/98876991-76413a00-244d-11eb-911d-b39123b8150c.png)

**Comment by francois-normandin** [comment]
available in release 1.1.0

**Comment by joerghampel** [comment]
Thank you, @francois-normandin! We will look into leveraging this in our tools next week. I'll let you know in case anything comes up.

**Comment by joerghampel** [comment]
@francois-normandin after two years, we finally got around to implement this feature into our own Release Automation Tools. 

I had hoped to be able to receive an event for each single test, so we can output what's happening while the whole test suite is executed. Is this something that would fit with the current architecture, and are there any plans to implement this?
